[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datacx"
version = "0.1.0"
description = "Data Connectors for all data sources"
readme = "README.md"
authors = [{ name = "Vinish M", email = "vinishuchiha@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache License 2.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["connectors", "data reader", "dataconnector"]
dependencies = [
    "boto3 >= 1.26.93",
    "google-cloud-storage >= 2.7.0",
    "azure-storage-blob >= 12.15.0",
    "pandas >= 1.0.0",
    "PyYAML",
    "connectorx",
    'tomli; python_version < "3.11"',
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/VinishUchiha/datacx"

